import type { Metadata } from "next";
import "./globals.css";
import NavbarWrapper from "@/layouts/Navbar/NavbarWrapper";
import { Roboto } from "next/font/google";

const robotoFont = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${robotoFont.className}`}
      >
        <NavbarWrapper />
        {children}
      </body>
    </html>
  );
}
